/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import handler from './api/data';

import SearchInput from '../components/searchInput';
import Comment from '../components/comment';

export default function Home({ data }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Comment App UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-100'>

        <SearchInput />
        <div>
          {
            data.map((chat, index) => {
              return (
                <Comment key={chat.id} chat={chat} index={index} />
              )
            })
          }

        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(ctx) {
  const data = await handler();
  return {
    props: {
      data
    }
  }
}
